# Sheldon configuration file
#
# See https://sheldon.cli.rs
#
# Also heavily inspired by https://github.com/rossmacarthur/dotfiles/tree/trunk

shell = "zsh"

[templates]
defer = """{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}"""
defer-more = """{{ hooks?.pre | nl }}{% for file in files %}zsh-defer -t 0.5 source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}"""

# Loading indicator
# -----------------

[plugins.show]
local = "~/.zsh/plugins/loading"

# Completions
# -----------

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# Sourced
# -------

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Some of the functions may get used elsewhere
# so we do not defer loading
[plugins.functions]
local = "~/.zsh/plugins"

# Deferred plugins
# ----------------

[plugins.aliases]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.fzf]
github = "junegunn/fzf"
use = ["shell/completion.zsh", "shell/key-bindings.zsh"]
apply = ["defer"]

[plugins.fzf-completions]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
use = ["{{ name }}.zsh"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]
hooks.pre = "export YSU_MODE=ALL"

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.fnm]
local = "~/.zsh/plugins"
apply = ["defer"]

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
apply = ["defer"]

[plugins.mcfly]
github = "cantino/mcfly"
apply = ["defer"]

# This works best if it is placed last.
[plugins.compinit]
local = "~/.zsh/plugins"
apply = ["defer"]

# Loading indicator
# -----------------

[plugins.hide]
local = "~/.zsh/plugins/loading"
apply = ["defer-more"]
