require('config.plugins.diffview')
require('config.plugins.fzf-lua')
require('config.plugins.gitsigns')
require('config.plugins.nvim-tree')
require('config.plugins.web-devicons')
require('config.plugins.which-key')
